name: progress_soft_ass
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # ? localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  dartz: ^0.10.1
  get_it: ^7.6.0

  # ? network
  dio: ^5.2.1+1
  pretty_dio_logger: ^1.3.1

  # ? resize
  flutter_screenutil: ^5.9.3

  # ? state management
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2

  # ? utils
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.7
  octo_image: ^1.0.2
  lottie: ^2.4.0
  rename: ^2.1.1    # rename the app
  rxdart: ^0.27.7
  url_launcher: ^6.1.11
  country_codes: ^3.1.0+2
  numberpicker: ^2.1.2
  pinput: ^5.0.0
  flutter_libphonenumber: ^2.2.3
  
  # ? test
  mockito: ^5.4.2
  equatable: ^2.0.5

  # ? platforms packages
  package_info_plus: ^4.0.2
  share_plus: ^7.0.2
  in_app_review: ^2.0.6
  shared_preferences: ^2.2.0
  image_picker: ^1.0.0
  flutter_local_notifications: ^15.0.0

  # ? firebase
  firebase_core: ^3.2.0
  firebase_messaging: ^15.0.3
  firebase_analytics: ^11.2.0
  firebase_remote_config: ^5.0.3
  cloud_firestore: ^5.1.0
  firebase_auth: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  flutter_launcher_icons: "^0.13.1"
  change_app_package_name: ^1.1.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_app.png"
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/json/